import os
import time
import logging
from google import genai
from google.genai import types
from typing import List

from models import FrameInfo

GHIBLI_VIDEO_PROMPT = (
    "A cinematic, haunting video in a Studio Ghibli homage style. "
    "Lush, vibrant watercolor backgrounds, distinct clean character/object outlines, and soft, magical lighting. "
    "The camera slowly pans across the scene, retaining the exact structural composition of the frames. "
    "Gentle, ambient movement. Hand-drawn anime style reminiscent of classic 90s animation."
)

def generate_scene_video(stylized_frames: List[FrameInfo], output_path: str, duration_seconds: str = "4"):
    """
    Uses Veo 3.1 to generate a video for a specific scene, utilizing all available stylized frames as context.
    stylized_frames: list of dicts [{"path": ...}, ...]
    """
    client = genai.Client()
    
    logging.info(f"Generating Veo 3.1 video for scene ({len(stylized_frames)} frames) -> {output_path} (Duration: {duration_seconds}s)")
    
    if not stylized_frames:
        logging.warning("No frames provided for Veo generation.")
        return

    # Prepare first image
    with open(stylized_frames[0]["path"], "rb") as f:
        first_image = types.Image(image_bytes=f.read(), mime_type="image/png")

    kwargs = {
        "model": "veo-3.1-fast-generate-preview",
        "prompt": GHIBLI_VIDEO_PROMPT,
        "image": first_image
    }
    
    config_kwargs = {}
    config_kwargs["duration_seconds"] = duration_seconds
    config_kwargs["person_generation"] = "allow_adult"
    
    if len(stylized_frames) >= 2:
        # Use simple interpolation between first and last frame of the scene
        with open(stylized_frames[-1]["path"], "rb") as f:
            last_image = types.Image(image_bytes=f.read(), mime_type="image/png")
        config_kwargs["last_frame"] = last_image

    kwargs["config"] = types.GenerateVideosConfig(**config_kwargs)

    operation = client.models.generate_videos(**kwargs)

    # Poll the operation status
    while not operation.done:
        logging.info("Waiting for Veo 3.1 video generation to complete... (this may take a few minutes)")
        time.sleep(10)
        operation = client.operations.get(operation)

    # Download the video
    if operation.response.generated_videos:
        video = operation.response.generated_videos[0]
        
        # Ensure output directory exists
        out_dir = os.path.dirname(output_path)
        if out_dir and not os.path.exists(out_dir):
            os.makedirs(out_dir)
            
        client.files.download(file=video.video)
        try:
             video.video.save(output_path)
             logging.info(f"Veo 3.1 generated video saved to {output_path}")
        except AttributeError:
             logging.warning("Could not save video directly. Check the SDK documentation.")
    else:
        logging.error("No video was generated by Veo.")
        
    return output_path
