import os
import time
import logging
from google import genai
from google.genai import types
from google.api_core import exceptions
from typing import List, Optional

from models import FrameInfo, UsageMetrics, QuotaExceededError

GHIBLI_VIDEO_PROMPT = (
    "A cinematic, haunting video in a Studio Ghibli homage style. "
    "Lush, vibrant watercolor backgrounds, distinct clean character/object outlines, and soft, magical lighting. "
    "The camera slowly pans across the scene, retaining the exact structural composition of the frames. "
    "Gentle, ambient movement. Hand-drawn anime style reminiscent of classic 90s animation."
)

def generate_scene_video(stylized_frames: List[FrameInfo], output_path: str, duration_seconds: str = "4", scene_description: str = "", metrics: UsageMetrics = None):
    """
    Uses Veo 3.1 to generate a video for a specific scene.
    Uses scene_description to guide the generation.
    """
    client = genai.Client()
    
    logging.info(f"Generating Veo 3.1 video for scene ({len(stylized_frames)} frames) -> {output_path} (Duration: {duration_seconds}s)")
    
    if not stylized_frames:
        logging.warning("No frames provided for Veo generation.")
        return

    # Prepare first image
    with open(stylized_frames[0]["path"], "rb") as f:
        first_image = types.Image(image_bytes=f.read(), mime_type="image/png")

    # Build smart video prompt
    context_prefix = f"Video of: {scene_description}. " if scene_description else ""
    full_video_prompt = f"{context_prefix}{GHIBLI_VIDEO_PROMPT}"

    kwargs = {
        "model": "veo-3.1-fast-generate-preview",
        "prompt": full_video_prompt,
        "image": first_image
    }
    
    config_kwargs = {}
    config_kwargs["duration_seconds"] = int(float(duration_seconds))
    config_kwargs["person_generation"] = "allow_adult"
    
    if len(stylized_frames) >= 2:
        # Use simple interpolation between first and last frame of the scene
        with open(stylized_frames[-1]["path"], "rb") as f:
            last_image = types.Image(image_bytes=f.read(), mime_type="image/png")
        config_kwargs["last_frame"] = last_image

    kwargs["config"] = types.GenerateVideosConfig(**config_kwargs)

    max_retries = 5
    operation = None
    for attempt in range(max_retries):
        try:
            operation = client.models.generate_videos(**kwargs)
            if metrics:
                metrics.videos_generated += 1
            break
        except exceptions.ResourceExhausted as e:
            error_msg = str(e).lower()
            if "quota" in error_msg or "per day" in error_msg:
                logging.error(f"Daily quota hit for Veo: {e}. Exiting so you can resume later.")
                raise QuotaExceededError("Veo daily quota exceeded.")
            
            wait_time = 60
            logging.warning(f"Veo rate limit hit (RPM). Waiting {wait_time}s... Error: {e}")
            time.sleep(wait_time)
        except Exception as e:
            logging.warning(f"Veo generation error on attempt {attempt+1}: {e}")
            if attempt < max_retries - 1:
                time.sleep(5 * (2 ** attempt))
            else:
                logging.error(f"Failed to initiate Veo generation after {max_retries} attempts.")
                return None

    if not operation:
        return None

    # Poll the operation status
    start_time = time.time()
    while not operation.done:
        elapsed = time.time() - start_time
        logging.info(f"Waiting for Veo 3.1 video generation ({output_path})... Elapsed: {elapsed:.1f}s")
        time.sleep(15)
        try:
            operation = client.operations.get(operation)
        except Exception as e:
            logging.warning(f"Error polling Veo operation: {e}. Retrying...")

    # Download the video
    if operation.response and operation.response.generated_videos:
        video = operation.response.generated_videos[0]
        
        # Ensure output directory exists
        out_dir = os.path.dirname(output_path)
        if out_dir and not os.path.exists(out_dir):
            os.makedirs(out_dir)
            
        try:
             client.files.download(file=video.video)
             video.video.save(output_path)
             logging.info(f"Veo 3.1 generated video saved to {output_path}")
        except Exception as e:
             logging.warning(f"Could not save video directly: {e}")
    else:
        logging.error(f"No video was generated by Veo. Error: {operation.error if operation.error else 'Unknown'}")
        
    return output_path
